version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: traveloop_postgres
    environment:
      POSTGRES_USER: traveloop_user
      POSTGRES_PASSWORD: traveloop_password
      POSTGRES_DB: traveloop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
